---
# Copyright 2020 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# Validate that the validation fails when the undercloud.conf does not contain
# a required parameter. In this case, container_images_file:
#
# [DEFAULT]
# local_interface = em0
# local_ip = 192.168.24.1/24
# undercloud_public_host = 192.168.24.2
# undercloud_admin_host = 192.168.24.3
# undercloud_nameservers = 172.16.0.1,10.0.0.1
# undercloud_ntp_servers=clock1.rdu2.redhat.com
# overcloud_domain_name=redhat.local
# undercloud_service_certificate = /undercloud.pem
# hieradata_override = /hiera_override.yaml
# enabled_hardware_types = ipmi,redfish
# custom_env_files = /skip_rhel_release.yaml
#
# [ctlplane-subnet]
# local_subnet = ctlplane-subnet
# cidr = 192.168.24.0/24
# dhcp_start = 192.168.24.5
# dhcp_end = 192.168.24.55
# gateway = 192.168.24.1
# inspection_iprange = 192.168.24.100,192.168.24.120
#
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: detect missing required parameter from conf
      block:
        - name: run validation check_undercloud_conf
          include_role:
            name: "check_undercloud_conf"
      rescue:
        - name: Clear host errors
          meta: clear_host_errors

        - name: Detect right error message
          fail:
            msg: "Test failed due to wrong error: {{ ansible_failed_result.results.0.msg }}"
          when:
            - not ansible_failed_result.results.0.msg |
              regex_search("^Property .* is required in .*$")

        - name: Status message
          debug:
            msg: "Detected undercloud.conf configuration issue!"

        - name: End play
          meta: end_play

    - name: Fail the test
      fail:
        msg: |
          A configuration issue should have been detected but it wasn't..
