---
- hosts: all
  pre_tasks:
    - name: Ensure output dirs
      file:
        path: "{{ ansible_user_dir }}/zuul-output/logs"
        state: directory

    - name: Ensure virtualenv is available
      include_role:
        name: ensure-virtualenv

    - name: Setup bindep
      pip:
        name: "bindep"
        virtualenv: "{{ ansible_user_dir }}/test-python"
        virtualenv_site_packages: true

    - name: Run bindep
      shell: |-
        . {{ ansible_user_dir }}/test-python/bin/activate
        {{ ansible_user_dir }}/{{ zuul.project.src_dir }}/scripts/bindep-install
      become: true
      changed_when: false

    - name: Ensure a recent version of pip is installed in virtualenv
      pip:
        name: "pip>=19.1.1"
        virtualenv: "{{ ansible_user_dir }}/test-python"
        virtualenv_command: "{{ ensure_pip_virtualenv_command }}"

    - name: Setup test-python
      pip:
        requirements: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/molecule-requirements.txt"
        virtualenv: "{{ ansible_user_dir }}/test-python"
        virtualenv_site_packages: true

  tasks:
    - name: Get Ansible Galaxy roles
      command: >-
        {{ ansible_user_dir }}/test-python/bin/ansible-galaxy install
        -fr
        {{ ansible_user_dir }}/{{ zuul.project.src_dir }}/ansible-role-requirements.yml
      environment:
        ANSIBLE_ROLES_PATH: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/roles/roles.galaxy"

  roles:
    - role: ensure-docker
