---

- hosts: all
  environment:
    ANSIBLE_LOG_PATH: "{{ ansible_user_dir }}/zuul-output/logs/ansible-execution.log"
  pre_tasks:

    - name: Set project path fact
      set_fact:
        tripleo_validations_project_path: "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/tripleo-validations'].src_dir }}"

    - name: Set role path fact
      set_fact:
        tripleo_validations_roles_paths:
          - "{{ tripleo_validations_project_path }}/roles/roles.galaxy/tripleo-ansible/tripleo_ansible/roles"
          - "{{ tripleo_validations_project_path }}/roles/roles.galaxy/tripleo-ansible/tripleo-ansible/tripleo_ansible/roles"
          - "{{ tripleo_validations_project_path }}/roles"
          - "/usr/share/ansible/roles"

  tasks:
    - name: Run role test job
      shell: |-
        . {{ ansible_user_dir }}/test-python/bin/activate
        . {{ tripleo_validations_project_path }}/ansible-test-env.rc
        pytest --color=no \
               --html={{ ansible_user_dir }}/zuul-output/logs/reports.html \
               --self-contained-html \
               --ansible-args='{{ tripleo_job_ansible_args | default("") }}' \
               {{ tripleo_validations_project_path }}/tests/test_molecule.py
      args:
        chdir: "{{ tripleo_validations_project_path }}/roles/{{ tripleo_validations_role_name }}"
        executable: /bin/bash
      environment:
        ANSIBLE_ROLE_PATH: "{{ tripleo_validations_roles_paths | join(':') }}"
