---
- name: List the available drives
  register: drive_list
  command: "ls /sys/class/block/"
  changed_when: False

- name: Detect whether the drive uses Advanced Format
  advanced_format: drive={{ item }}
  when: item is match("^sd.$")
  with_items: "{{ drive_list.stdout_lines }}"
