---
- name: Get Ironic Inspector swift auth_url
  become: true
  ini:
    path: "{{ ironic_inspector_conf_file }}"
    section: swift
    key: auth_url
  register: auth_url

- name: Get Ironic Inspector swift password
  become: true
  ini:
    path: "{{ ironic_inspector_conf_file }}"
    section: swift
    key: password
  register: password

- name: Check that switch vlans are present if used in nic-config files
  switch_vlans:
    path: "{{ network_environment_path }}"
    template_files: "{{ lookup('tht') }}"
    introspection_data: "{{ lookup('introspection_data',
                            auth_url=auth_url.value, password=password.value) }}"
