---
# Copyright 2019 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


- name: Converge
  hosts: all
  gather_facts: false

  tasks:
    - name: working detection
      include_role:
        name: undercloud_heat_purge_deleted

    - name: Validate failure
      block:
        - name: Override container_cli
          copy:
            dest: /undercloud.conf
            content: |
              [DEFAULT]
              container_cli = docker

        - name: run validation
          include_role:
            name: undercloud_heat_purge_deleted
      rescue:
        - name: Clear host errors
          meta: clear_host_errors

        - name: Test output
          debug:
            msg: The validation works! Ending play.

        - name: End play
          meta: end_play

    - name: Fail the validation at this point
      fail:
        msg: |
          The undercloud_heat_purge_deleted validation failed to detect
          missing cron job.
