---
metadata:
  name: Undercloud Services Debug Check
  description: >
    The undercloud's openstack services should _not_ have debug enabled.
    This will check if debug is enabled on undercloud services.
    If debug is enabled, the root filesystem can fill up quickly, and
    is not a good thing.
  groups:
    - pre-deployment
