---
- name: Check if ceph-ansible is installed
  shell: rpm -q ceph-ansible || true
  args:
    warn: false
  changed_when: false
  ignore_errors: true
  register: ceph_ansible_installed

- name: Warn about missing ceph-ansible
  warn:
    msg: If planning to use Ceph, it is necessary to install the ceph-ansible package on the undercloud
  when:
    - ceph_ansible_installed.stdout.find('is not installed') != -1
    - not fail_without_ceph_ansible|default(false)|bool

- name: Fail if ceph-ansible is missing
  fail:
    msg: If planning to use Ceph, it is necessary to install the ceph-ansible package on the undercloud
  when:
    - ceph_ansible_installed.stdout.find('is not installed') != -1
    - fail_without_ceph_ansible|default(false)|bool

- name: Get ceph-ansible repository
  shell: "yum info ceph-ansible | awk '/From repo/ {print $4}'"
  register: repo
  changed_when: false

- name: Fail if ceph-ansible doesn't belong to the specified repo
  fail:
    msg: "Make sure ceph-ansible package is installed from {{ ceph_ansible_repo }} \
          or configure the repo name you intend to install it from using the \
          'CephAnsibleRepo' variable provided by tripleo-heat-templates"
  when:
    - (repo.stdout | length == 0 or repo.stdout != "{{ ceph_ansible_repo }}")
    - fail_without_ceph_ansible|default(false)|bool
