---
driver:
  name: docker

log: true

platforms:
  - name: centos7
    hostname: centos7
    image: centos:7
    pkg_extras: python-setuptools python-enum34 PyYAML
    easy_install:
      - pip
    environment: &env
      http_proxy: "{{ lookup('env', 'http_proxy') }}"
      https_proxy: "{{ lookup('env', 'https_proxy') }}"

  - name: fedora28
    hostname: fedora28
    image: fedora:28
    pkg_extras: python*-setuptools python*-enum PyYAML
    environment:
      <<: *env

provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml
    ANSIBLE_LIBRARY: "../../../../library"

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy

lint:
  enabled: false

verifier:
  name: testinfra
  lint:
    name: flake8
