---
- hosts: ceph_mon
  vars:
    metadata:
      name: Check the status of the ceph cluster
      description: >
        Uses `ceph health` to check if cluster is in HEALTH_WARN state
        and prints a debug message.

      groups:
        - post-deployment
        - post-ceph
    tripleo_delegate_to: "{{ groups['ceph_mon'] | default([]) }}"
    osd_percentage_min: 0
  tasks:
    - include_role:
        name: ceph
        tasks_from: ceph-health
