---
- hosts: "{{ controller_rolename | default('Controller') }}"
  vars:
    metadata:
      name: Verify that keystone admin token is disabled
      description: |
        This validation checks that policy file of manilas configuration folder inside of the container,exists.
      groups:
        - post-deployment
        - post-update
        - pre-update
      categories:
        - controller
      products:
        - tripleo
        - manila
    manilas_policy_file: "/var/lib/config-data/puppet-generated/manila/etc/manila/policy.yaml"
  roles:
    - check_manila_policy_file
