---
- hosts: undercloud
  gather_facts: false
  vars:
    metadata:
      name: Check DockerInsecureRegistryAddress parameter points to correct UC hostname
      description: |
        This validation checks the DockerInsecureRegistryAddress parameter
        points to the right UC hostname
      groups:
        - pre-overcloud-upgrade
        - post-update
    check_uc_hostname_debug: false
  roles:
    - check_uc_hostname
