---
- hosts: undercloud, allovercloud
  vars:
    metadata:
      name: Ensure container status
      description: >
        Detect failed containers and raise an error.
      groups:
        - pre-upgrade
        - pre-update
        - post-deployment
        - post-upgrade
  roles:
    - container_status
