---
- hosts: undercloud, allovercloud
  vars:
    metadata:
      name: Ensure container status
      description: |
        Detect failed containers and raise an error.
      groups:
        - backup-and-restore
        - pre-upgrade
        - pre-update
        - post-deployment
        - post-upgrade
        - post-update
      categories:
        - container
        - undercloud
        - overcloud
        - undercloud-config
      products:
        - tripleo
  roles:
    - container_status
