---
- hosts: all
  vars:
    metadata:
      name: FRR Daemons Status Check
      description: |
        Runs 'show watchfrr' and checks for any non-operational daemon.

        A failed status post-deployment indicates at least one enabled FRR
        daemon is not operational.
      groups:
        - post-deployment
        - post-update
        - pre-update
      categories:
        - container
        - frrouting
        - iprouting
        - undercloud
        - overcloud
      products:
        - tripleo
  roles:
    - frr_status
