---
- hosts: undercloud
  vars:
    metadata:
      name: Verify image-serve service is working and answering
      description: |
        Ensures image-serve vhost is configured and httpd is running.
      groups:
        - backup-and-restore
        - pre-upgrade
        - post-deployment
        - post-upgrade
        - post-update
        - pre-update
      categories:
        - httpd
        - container
        - registry
        - undercloud
      products:
        - tripleo
  roles:
    - image_serve
