---
- hosts: Controller
  vars:
    metadata:
      name: Neutron Sanity Check
      description: >
        Run `neutron-sanity-check` on the controller nodes to find out
        potential issues with Neutron's configuration.

        The tool expects all the configuration files that are passed
        to the Neutron services.

      groups:
        - post-deployment

    # The list of Neutron configuration files and directories that
    # will be passed to the Neutron services. The order is important
    # here: the values in later files take precedence.
    configs:
    - /etc/neutron/neutron.conf
    - /usr/share/neutron/neutron-dist.conf
    - /etc/neutron/metadata_agent.ini
    - /etc/neutron/dhcp_agent.ini
    - /etc/neutron/fwaas_driver.ini
    - /etc/neutron/l3_agent.ini
    - /usr/share/neutron/neutron-lbaas-dist.conf
    - /etc/neutron/lbaas_agent.ini

  roles:
    - neutron-sanity-check
