---
- hosts: "{{ controller_rolename | default('Controller') }}"
  gather_facts: false
  vars:
    metadata:
      name: Neutron Sanity Check
      description: >
        Run `neutron-sanity-check` on the controller nodes to find out
        potential issues with Neutron's configuration.

        The tool expects all the configuration files that are passed
        to the Neutron services.

      groups:
        - post-deployment

  roles:
    - neutron_sanity_check
