---
- hosts: undercloud
  vars:
    metadata:
      name: Check node disk configuration
      description: >
        Check node disk numbers and sizes and whether root device hints are set.
      groups:
        - pre-deployment
    ironic_conf_file: "/var/lib/config-data/puppet-generated/ironic/etc/ironic/ironic.conf"
  roles:
    - node-disks
