---
- hosts: nova_libvirt
  gather_facts: false
  vars:
    metadata:
      name: Check nova sVirt support
      description: |
        Ensures all running VM are correctly protected with sVirt
      groups:
        - post-deployment
        - post-upgrade
        - post-update
        - pre-update
      categories:
        - compute
        - selinux
        - security
      products:
        - tripleo
  roles:
    - nova_svirt
