---
- hosts: overcloud
  vars:
    metadata:
      name: Verify all deployed nodes have their clock synchronised
      description: >
        Each overcloud node should have their clocks synchronised.

        The deployment should configure and run chronyd. This validation verifies
        that it is indeed running and connected to an NTP server on all nodes.
      groups:
      - post-deployment
  roles:
    - ntp
