---
- hosts: "{{ controller_rolename | default('Controller') }}"
  vars:
    metadata:
      name: Rabbitmq limits
      description: |
        Make sure the rabbitmq file descriptor limits are set to reasonable values.
      groups:
        - post-deployment
        - post-update
        - pre-update
      categories:
        - container
        - messaging
        - broker
      products:
        - tripleo
        - rabbitmq
    min_fd_limit: 16384
  roles:
    - rabbitmq_limits
