---
- hosts: all
  vars:
    metadata:
      name: System encoding
      description: >-
        Ensure the local is unicode
      groups:
        - pre-deployment
        - pre-upgrade
        - pre-update
    system_encoding_debug: false
  roles:
    - system_encoding
