---
- hosts: undercloud
  vars:
    metadata:
      name: Undercloud Neutron Sanity Check
      description: >
        Run `neutron-sanity-check` on the undercloud node to find out
        potential issues with Neutron's configuration.

        The tool expects all the configuration files that are passed
        to the Neutron services.

      groups:
        - pre-introspection

    # The list of Neutron configuration files and directories that
    # will be passed to the Neutron services. The order is important
    # here: the values in later files take precedence.
    configs:
      - /etc/neutron/neutron.conf
      - /usr/share/neutron/neutron-dist.conf
      - /etc/neutron/metadata_agent.ini
      - /etc/neutron/dhcp_agent.ini
      - /etc/neutron/plugins/ml2/openvswitch_agent.ini
      - /etc/neutron/l3_agent.ini

  roles:
    - neutron_sanity_check
