---
- hosts: undercloud
  vars:
    metadata:
      name: Verify undercloud fits the disk space requirements
      description: >
        Make sure that the root partition on the undercloud node has enough
        free space.

        http://tripleo.org/install/environments/baremetal.html#minimum-system-requirements
      groups:
        - prep
        - pre-introspection
    volumes:
      - {mount: /var/lib/docker,      min_size: 10}
      - {mount: /var/lib/config-data, min_size: 3}
      - {mount: /var/log,             min_size: 3}
      - {mount: /usr,                 min_size: 5}
      - {mount: /var,                 min_size: 20}
      - {mount: /,                    min_size: 25}

  roles:
    - undercloud-disk-space
